---

  - name: Install nginx web server and —Åomponents
    yum:
      name:
        - nginx
        - php
        - php-fpm
      state: present

  - name: Delete default config nginx
    file:
      path: /etc/nginx/conf.d/default.conf
      state: absent

  - name: Copy a new nginx config
    template:
      src: default.conf.j2
      dest: /etc/nginx/conf.d/allhosts.conf

  - name: Copy index.php
    copy:
      src: index.php
      dest: /var/www/{{ domain_name }}
    notify:
      - Restart nginx
      - Restart php-fpm

