---
- hosts: nginx
  vars_files:
    - vars.yml

  tasks:
    - name: Install nginx web server and сomponents
      yum:
        name: 
          - nginx
          - php
          - php-fpm
        state: present

    - name: Install certbot
      yum:
        name:
          - certbot

    - name: Create domain directory
      file:
        name: /var/www/{{ domain_name }}
        state: directory

    - name: Create letsencrypt certificate
      shell: certbot certonly -n --webroot -w /var/www/{{ domain_name }} -m {{ email }} --agree-tos -d {{ domain_name }}
      args:
        creates: /etc/letsencrypt/live/{{ domain_name }}

    - name: Generate dhparams
      shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
      args:
        creates: /etc/nginx/dhparams.pem

    - name: Copy ssl additionally options file for nginx
      copy:
        src: templates/options-ssl-nginx.conf
        dest: /etc/nginx/

    - name: Delete default config nginx
      file:
        path: /etc/nginx/conf.d/default.conf
        state: absent

    - name: Copy a new nginx config
      template:
        src: templates/default.conf.j2
        dest: /etc/nginx/conf.d/allhosts.conf

    - name: Allow nginx to listen on tcp port 7080 and 7443
      seport:
        ports: 7080,7443
        proto: tcp
        setype: http_port_t
        state: present

    - name: firewall add https
      firewalld:
        service: https
        permanent: yes
        state: enabled
    - name: firewall add http
      firewalld:
        service: http
        permanent: yes
        state: enabled
    - name: firewall add 7080
      firewalld:
        port: 7080/tcp
        permanent: yes
        state: enabled
    - name: firewall add 7443
      firewalld:
        port: 7443/tcp
        permanent: yes
        state: enabled

    - name: Copy index.php
      copy:
        src: templates/index.php
        dest: /var/www/{{ domain_name }}

    - name: Add logger host to rsyslog
      shell: echo "*.* @@10.216.129.25:514" >> /etc/rsyslog.conf

    - name: Restart nginx
      service: name=nginx state=restarted

    - name: Restart php-fpm
      service: name=php-fpm state=restarted

    - name: Restart rsyslog
      service: name=rsyslog state=restarted

    - name: Reload firewalld
      shell: firewall-cmd --reload  

