---
  - name: Install python lib for selinux support
    yum:
      name:
        - policycoreutils-python
      state: present

  - name: Allow nginx to listen on tcp port 7080 and 7443
    seport:
      ports: 7080,7443
      proto: tcp
      setype: http_port_t
      state: present

  - name: Firewall add services http and https
    firewalld:
      service: "{{ item }}"
      permanent: yes
      state: enabled
    with_items:
      - https
      - http

  - name: Firewall add ports 7080 and 7443
    firewalld:
      port: "{{ item }}"
      permanent: yes
      state: enabled
    with_items:
      - '7080/tcp'
      - '7443/tcp'  
    notify:
      - Reload firewall
      
  - name: Add logger host to rsyslog
    shell: echo "*.* @@10.216.129.25:514" >> /etc/rsyslog.conf
    notify:
      - Restart rsyslog

