---
  - name: Install python lib
    yum:
      name:
        - policycoreutils-python
      state: present

  - name: Allow nginx to listen on tcp port 7080 and 7443
    seport:
      ports: 7080,7443
      proto: tcp
      setype: http_port_t
      state: present

  - name: firewall add https
    firewalld:
      service: https
      permanent: yes
      state: enabled
  - name: firewall add http
    firewalld:
      service: http
      permanent: yes
      state: enabled
  - name: firewall add 7080
    firewalld:
      port: 7080/tcp
      permanent: yes
      state: enabled
  - name: firewall add 7443
    firewalld:
      port: 7443/tcp
      permanent: yes
      state: enabled
    notify:
      - Reload firewall
      
  - name: Add logger host to rsyslog
    shell: echo "*.* @@10.216.129.25:514" >> /etc/rsyslog.conf
    notify:
      - Restart rsyslog

